
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.10.0
 * Query Engine version: 0edf323efd1d98336f3f0a68684b56f689b900d3
 */
Prisma.prismaVersion = {
  client: "7.10.0",
  engine: "0edf323efd1d98336f3f0a68684b56f689b900d3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ConnectedAccountScalarFieldEnum = {
  id: 'id',
  platform: 'platform',
  platformId: 'platformId',
  name: 'name',
  username: 'username',
  encryptedToken: 'encryptedToken',
  category: 'category',
  status: 'status',
  owner: 'owner',
  connectedOn: 'connectedOn',
  updatedAt: 'updatedAt',
  lastSyncedAt: 'lastSyncedAt',
  nameStatus: 'nameStatus',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  postCollectionId: 'postCollectionId',
  accountId: 'accountId',
  platform: 'platform',
  platformPostId: 'platformPostId',
  message: 'message',
  postLink: 'postLink',
  createdBy: 'createdBy',
  createdOn: 'createdOn',
  analytics: 'analytics',
  logs: 'logs',
  mediaUrls: 'mediaUrls'
};

exports.Prisma.PostCollectionScalarFieldEnum = {
  id: 'id',
  content: 'content',
  mediaUrls: 'mediaUrls',
  status: 'status',
  author: 'author',
  createdAt: 'createdAt',
  postsId: 'postsId',
  accountIds: 'accountIds',
  platforms: 'platforms',
  ctaType: 'ctaType',
  ctaLink: 'ctaLink',
  publishedAt: 'publishedAt',
  scheduledAt: 'scheduledAt',
  originalPostCollectionId: 'originalPostCollectionId'
};

exports.Prisma.UploadScalarFieldEnum = {
  id: 'id',
  contentName: 'contentName',
  fileName: 'fileName',
  fileSize: 'fileSize',
  fileType: 'fileType',
  uploadedBy: 'uploadedBy',
  filePath: 'filePath',
  platform: 'platform',
  contentId: 'contentId',
  uploadedOn: 'uploadedOn'
};

exports.Prisma.SyncLogScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  status: 'status',
  syncedAt: 'syncedAt',
  postsSynced: 'postsSynced',
  errorMessage: 'errorMessage',
  range: 'range',
  details: 'details'
};

exports.Prisma.SyncLogEntryScalarFieldEnum = {
  id: 'id',
  type: 'type',
  platform: 'platform',
  forProfile: 'forProfile',
  sinceTime: 'sinceTime',
  toTime: 'toTime',
  moreInfo: 'moreInfo',
  createdOn: 'createdOn'
};

exports.Prisma.SpaceScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.SpaceAssetScalarFieldEnum = {
  id: 'id',
  spaceId: 'spaceId',
  platform: 'platform',
  assetId: 'assetId'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  moreDetails: 'moreDetails',
  contactId: 'contactId',
  contactName: 'contactName',
  channelId: 'channelId',
  platform: 'platform',
  lastMessage: 'lastMessage',
  lastMessageAt: 'lastMessageAt',
  unread: 'unread',
  avatar: 'avatar',
  createdAt: 'createdAt'
};

exports.Prisma.ConversationMessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  platformMessageId: 'platformMessageId',
  text: 'text',
  sender: 'sender',
  timestamp: 'timestamp',
  type: 'type',
  callEvent: 'callEvent'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  platform: 'platform',
  platformMessageId: 'platformMessageId',
  text: 'text',
  sender: 'sender',
  timestamp: 'timestamp',
  type: 'type',
  moreDetails: 'moreDetails',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SystemAlertScalarFieldEnum = {
  id: 'id',
  type: 'type',
  platform: 'platform',
  payload: 'payload',
  timestamp: 'timestamp'
};

exports.Prisma.SystemConfigScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CommentorScalarFieldEnum = {
  id: 'id',
  platform: 'platform',
  onProfile: 'onProfile',
  platformUserId: 'platformUserId',
  name: 'name',
  firstInteraction: 'firstInteraction',
  createdAt: 'createdAt'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  by: 'by',
  onProfile: 'onProfile',
  comment: 'comment',
  on: 'on',
  platform: 'platform',
  platformCommentId: 'platformCommentId',
  postId: 'postId',
  postMessage: 'postMessage',
  permalinkUrl: 'permalinkUrl',
  createdAt: 'createdAt'
};

exports.Prisma.IdentityUnifiedScalarFieldEnum = {
  id: 'id',
  name: 'name',
  moreInfo: 'moreInfo',
  createdOn: 'createdOn'
};

exports.Prisma.IdentityPlatformScalarFieldEnum = {
  id: 'id',
  platUserId: 'platUserId',
  platform: 'platform',
  unifiedId: 'unifiedId'
};

exports.Prisma.FacebookCommentScalarFieldEnum = {
  id: 'id',
  psid: 'psid',
  comment: 'comment',
  commentedOn: 'commentedOn',
  moreInfo: 'moreInfo'
};

exports.Prisma.PostCommentScalarFieldEnum = {
  id: 'id',
  commentId: 'commentId',
  postId: 'postId',
  platform: 'platform',
  commentedOn: 'commentedOn',
  commenter: 'commenter',
  commentText: 'commentText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InstagramLiveCommentScalarFieldEnum = {
  id: 'id',
  commentId: 'commentId',
  mediaId: 'mediaId',
  mediaProductType: 'mediaProductType',
  fromId: 'fromId',
  fromUsername: 'fromUsername',
  selfIgScopedId: 'selfIgScopedId',
  text: 'text',
  payload: 'payload',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InstagramMessageScalarFieldEnum = {
  id: 'id',
  senderId: 'senderId',
  recipientId: 'recipientId',
  eventTimestamp: 'eventTimestamp',
  messageMid: 'messageMid',
  messageText: 'messageText',
  numEdit: 'numEdit',
  payload: 'payload',
  createdAt: 'createdAt',
  reactionSummary: 'reactionSummary'
};

exports.Prisma.InstagramMessageAttachmentScalarFieldEnum = {
  id: 'id',
  instagramMessageId: 'instagramMessageId',
  platformAttachmentId: 'platformAttachmentId',
  attachmentType: 'attachmentType',
  mediaUrl: 'mediaUrl',
  thumbnailUrl: 'thumbnailUrl',
  permalink: 'permalink',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  connectionId: 'connectionId',
  displayName: 'displayName',
  displayImage: 'displayImage',
  neupId: 'neupId',
  type: 'type',
  createdOn: 'createdOn',
  status: 'status',
  moreDetails: 'moreDetails'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  ConnectedAccount: 'ConnectedAccount',
  Post: 'Post',
  PostCollection: 'PostCollection',
  Upload: 'Upload',
  SyncLog: 'SyncLog',
  SyncLogEntry: 'SyncLogEntry',
  Space: 'Space',
  SpaceAsset: 'SpaceAsset',
  Conversation: 'Conversation',
  ConversationMessage: 'ConversationMessage',
  Message: 'Message',
  SystemAlert: 'SystemAlert',
  SystemConfig: 'SystemConfig',
  Commentor: 'Commentor',
  Comment: 'Comment',
  IdentityUnified: 'IdentityUnified',
  IdentityPlatform: 'IdentityPlatform',
  FacebookComment: 'FacebookComment',
  PostComment: 'PostComment',
  InstagramLiveComment: 'InstagramLiveComment',
  InstagramMessage: 'InstagramMessage',
  InstagramMessageAttachment: 'InstagramMessageAttachment',
  Account: 'Account'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
