CREATE TABLE IF NOT EXISTS "accounts" (
    "account_id" TEXT NOT NULL,
    CONSTRAINT "accounts_pkey" PRIMARY KEY ("account_id")
);

ALTER TABLE "accounts"
    ADD COLUMN IF NOT EXISTS "display_name" TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "display_image" TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS "neupid" TEXT,
    ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'individual',
    ADD COLUMN IF NOT EXISTS "created_on" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS "more_details" JSONB;
